server:
  port: 8180
spring:
  profiles:
    active: dev
  application:
    name: service-statistics
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos 服务地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_statistics?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1 #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8 #最大空闲连接，默认8
        min-idle: 0 #最小空闲连接，默认0
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:org/clxmm/service/statistics/mapper/xml/*.xml

ribbon:
  ConnectTimeout: 10000  #连接建立的超时时长，默认1秒
  ReadTimeout: 1000  #处理请求的超时时间，默认为1秒

feign:
  sentinel:
    enabled: true
