server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB


aliyun:
  vod:
    keyid: LTAI4GKzHeJ5r6qFgNszfkWv
    keysecret: xpHTMK1tJhCyzed3YTpT4dIN45wtq7
    templateGroupId: VOD_NO_TRANSCODE   #转码模板组id
    workflowId: 你配置的工作流id #工作流id