server:
  port: 8170
spring:
  profiles:
    active: dev
  application:
    name: service-trade
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos 服务地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_trade?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1 #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8 #最大空闲连接，默认8
        min-idle: 0 #最小空闲连接，默认0
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:org/clxmm/service/edu/mapper/xml/*.xml

weixin:
  pay:
    #关联的公众号appid
    appId: wxf913bfa3a2c7eeeb
      #商户号
    partner: 1543338551
      #商户key
    partnerKey: atguigu3b0kn9g5v426MKfHQH7X8rKwb
      #回调地址
    notifyUrl: http://imhelen.free.idcfengye.com/api/trade/weixin-pay/callback/notify

ribbon:
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

feign:
  sentinel:
    enabled: true