spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cach
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1

mybatis:
  configuration:
    map-underscore-to-camel-case: true


