server:
  port: 8081



person:
  name: pp${random.value}
  age: ${random.int}
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    - w
    - i
    - r
  dog:
    name: ${person.hello:hello}_dog
    age: 3


###

spring:
  profiles:
    active: dev


#### 多文档块
---
server:
  port: 9004
spring:
  profiles: dev

---
server:
  port: 9005
spring:
  profiles: prod




