server:
  port: 9110
spring:
  profiles:
    active: dev
  application:
    name: infrastructure-apigateway # 服务名
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # gateway可以发现nacos中的微服务
      routes:
        - id: service-deu
#          uri: http://localhost:8110
          uri: lb://service-edu  # lb：表示在集群环境下通过负载均衡的方式调用
          predicates:
            - Path=/user/**,/*/edu/**  #
          filters:
            - SetStatus=220 # 修改返回状态码
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/*/cms/**
        - id: service-oss
          uri: lb://service-cms
          predicates:
            - Path=/*/oss/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-trade
          uri: lb://service-trade
          predicates:
            - Path=/*/trade/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**

    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址